apiVersion: v1
kind: Service
metadata:
  name: oracle-db
  labels:
    app: oracle-db
    service: oracle-db
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: oracle-db
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oracle-db-serviceaccount
  labels:
    account: oracle-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-db-test
  labels:
    app: oracle-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-db
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: oracle-db
    spec:
      volumes:
        - name: wallet
          secret:
            secretName: oracle-db-wallet
      containers:
        - name: oracle-db-health-check
          volumeMounts:
            - name: wallet
              # mountPath must coincide with the one selected for the wallet_location env variable (used to set the oracle.net.wallet_location variable)
              mountPath: $ORACLEDB_WALLET_LOCATION
              readOnly: true
          image: quay.io/ugiordan/oracle-wallet-secret
          imagePullPolicy: Always
          env:
            - name: URL
              valueFrom:
                secretKeyRef:
                  name: oracle-jdbc-env
                  key: url
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: oracle-jdbc-env
                  key: user
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oracle-jdbc-env
                  key: password
            - name: WALLET_LOCATION
              valueFrom:
                secretKeyRef:
                  name: oracle-jdbc-env
                  key: wallet_location
          ports:
            - containerPort: 8080